global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'observability-system'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          instance: 'localhost'

  - job_name: 'order-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['order-service:8001']
        labels:
          service: 'order-service'
          environment: 'development'

  - job_name: 'warehouse-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['warehouse-service:8002']
        labels:
          service: 'warehouse-service'
          environment: 'development'
