apiVersion: apps/v1
kind: Deployment
metadata:
  name: warehouse-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: warehouse-service
  template:
    metadata:
      labels:
        app: warehouse-service
    spec:
      containers:
      - name: warehouse-service
        image: warehouse-service:latest
        ports:
        - containerPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: warehouse-service
spec:
  selector:
    app: warehouse-service
  ports:
  - port: 8002
    targetPort: 8002
  type: LoadBalancer
